#name : PR Test
#
#on:
##  push:
##   branches: [ test ]
#  pull_request:
#    branches: [ test ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest # (3)
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2 # (4)
#
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v1 # (5)
#        with:
#          java-version: 1.8
#
#
#      - name: run test code
#        run: ./gradlew test
#
#      - name: if fail
#        uses: actions/github-script@0.2.0  # github-script 액션을 사용한다.
#        with:
#           github-token: ${{github.token}}  # github token을 선언해준다
#           script: |                        # script에 원하는 스크립트를 작성
#             const ref = "${{github.ref}}"
#             const pull_number = Number(ref.split("/")[2])
#             await github.pulls.createReview({
#               ...context.repo,
#               pull_number,
#               body:"테스트코드를 다시 확인해주세요. ",
#               event: "REQUEST_CHANGES"
#            })
#          await github.pulls.update({
#            ...context.repo,
#            pull_number,
#            state: "closed"
#          })
#      if: failure()